<a href="https://colab.research.google.com/github/SanjaySrivastav56/codealpha_tasks-/blob/main/pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10,23,56,78,64,90])
s

0    10
1    23
2    56
3    78
4    64
5    90
dtype: int64

In [ ]:
index = ["apple","banana","grapes","orange","strawberry", "kiwi"]
s.index = index
s

apple         10
banana        23
grapes        56
orange        78
strawberry    64
kiwi          90
dtype: int64

In [ ]:
import pandas as pd
s = pd.Series([10,23,56,78,64,90])
index = ["apple","banana","grapes","orange","strawberry", "kiwi"]
s.index = index
s['orange']

np.int64(78)

In [ ]:
s.loc["grapes"]

np.int64(56)

In [ ]:
 s.loc["banana":"strawberry"]

banana        23
grapes        56
orange        78
strawberry    64
dtype: int64

In [ ]:
 s.name = "calories"

In [ ]:
s

apple         10
banana        23
grapes        56
orange        78
strawberry    64
kiwi          90
Name: calories, dtype: int64

In [ ]:
 fruits_protein = {
     "avacado" : 2.0,
     "guava" : 2.6,
     "blackberries" : 2.0,
     "oranges" : 0.9,
    "kiwi" :1.1
 }

In [ ]:
s2 = pd.Series(fruits_protein, name = "protein")
s2

avacado         2.0
guava           2.6
blackberries    2.0
oranges         0.9
kiwi            1.1
Name: protein, dtype: float64

In [ ]:
#conditional selection
s2>1

avacado          True
guava            True
blackberries     True
oranges         False
kiwi             True
Name: protein, dtype: bool

In [ ]:
s2[s2>1]

avacado         2.0
guava           2.6
blackberries    2.0
kiwi            1.1
Name: protein, dtype: float64

In [ ]:
#logical operators & | ~
s2[(s2>0.5) & (s2<2.0)]

oranges    0.9
kiwi       1.1
Name: protein, dtype: float64

In [ ]:
s2[(s2<=0.3) | (s2>1.0)]

avacado         2.0
guava           2.6
blackberries    2.0
kiwi            1.1
Name: protein, dtype: float64

In [ ]:
s2[~(s2>1)]

oranges    0.9
Name: protein, dtype: float64

In [ ]:
#modifying in series
s2["kiwi"] = 2.4

In [ ]:
s2

avacado         2.0
guava           2.6
blackberries    2.0
oranges         0.9
kiwi            2.4
Name: protein, dtype: float64

In [ ]:
s2

avacado         2.0
guava           2.6
blackberries    2.0
oranges         0.9
kiwi            2.4
Name: protein, dtype: float64

In [ ]:
#dataframe
import pandas as pd

data = {
    "name" : ["sanjay","srivastav","Lakshman","Arjun"],
    "Age" : [20,30,35,18],
    "department" : ["IT","Finance","Charted Accountant","Bank Employee"],
    "Salary" : [10000,20000,30000,40000]
}
data

{'name': ['sanjay', 'srivastav', 'Lakshman', 'Arjun'],
 'Age': [20, 30, 35, 18],
 'department': ['IT', 'Finance', 'Charted Accountant', 'Bank Employee'],
 'Salary': [10000, 20000, 30000, 40000]}

In [ ]:
#creation of a dataframe
my_df = pd.DataFrame(data)
my_df

        name  Age          department  Salary
0     sanjay   20                  IT   10000
1  srivastav   30             Finance   20000
2   Lakshman   35  Charted Accountant   30000
3      Arjun   18       Bank Employee   40000

In [ ]:
my_df

        name  Age          department  Salary
0     sanjay   20                  IT   10000
1  srivastav   30             Finance   20000
2   Lakshman   35  Charted Accountant   30000
3      Arjun   18       Bank Employee   40000

In [ ]:
 #last two rows of dataset
my_df.tail(2)

       name  Age          department  Salary
2  Lakshman   35  Charted Accountant   30000
3     Arjun   18       Bank Employee   40000

In [ ]:
#first 2 rows of dataset
my_df.head(2)

        name  Age department  Salary
0     sanjay   20         IT   10000
1  srivastav   30    Finance   20000

In [ ]:
#iloc index location,retrieve data using index
my_df.iloc[1:3]

        name  Age          department  Salary
1  srivastav   30             Finance   20000
2   Lakshman   35  Charted Accountant   30000

In [ ]:
#loc gives all 3 rows for any last value
my_df.loc[1:3]

        name  Age          department  Salary
1  srivastav   30             Finance   20000
2   Lakshman   35  Charted Accountant   30000
3      Arjun   18       Bank Employee   40000

In [ ]:
#retrieving only 2 columns
my_df.iloc[1:3, [0,1]]

        name  Age
1  srivastav   30
2   Lakshman   35

In [ ]:
#:2 that will allow only first 2 columns in the output
my_df.loc[1:3, my_df.columns[:2]]

        name  Age
1  srivastav   30
2   Lakshman   35
3      Arjun   18

In [ ]:
#retrieve only single column
my_df["department"]

0                    IT
1               Finance
2    Charted Accountant
3         Bank Employee
Name: department, dtype: object

In [ ]:
my_df

        name  Age          department  Salary
0     sanjay   20                  IT   10000
1  srivastav   30             Finance   20000
2   Lakshman   35  Charted Accountant   30000
3      Arjun   18       Bank Employee   40000

In [ ]:
my_df

        name  Age          department  Salary
0     sanjay   20                  IT   10000
1  srivastav   30             Finance   20000
2   Lakshman   35  Charted Accountant   30000
3      Arjun   18       Bank Employee   40000

In [ ]:
#dropping in pandas entire column, for column axis = 1 for dropping use (df.drop) only
my_df.drop("Age", axis = 1)

        name          department  Salary
0     sanjay                  IT   10000
1  srivastav             Finance   20000
2   Lakshman  Charted Accountant   30000
3      Arjun       Bank Employee   40000

In [ ]:
#dropping enire row by using index value and axis = 0

my_df.drop(0,axis = 0)

        name  Age          department  Salary
1  srivastav   30             Finance   20000
2   Lakshman   35  Charted Accountant   30000
3      Arjun   18       Bank Employee   40000

In [ ]:
my_df
#after dropping some row and columns our main dataset is same

        name  Age          department  Salary
0     sanjay   20                  IT   10000
1  srivastav   30             Finance   20000
2   Lakshman   35  Charted Accountant   30000
3      Arjun   18       Bank Employee   40000

In [ ]:
#To modify the main table use inplace = True
#my_df.drop(0,axis = 0, inplace = True)
#by using this sanjay(1st row) will permanently deleted

In [ ]:
my_df.shape
#this means 4 rows and 4 columns

(4, 4)

In [ ]:
 #for retrieving other information we use function called info()
 my_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   Age         4 non-null      int64
 2   department  4 non-null      object
 3   Salary      4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
my_df.describe()
#statistical information on your data

             Age        Salary
count   4.000000      4.000000
mean   25.750000  25000.000000
std     8.098354  12909.944487
min    18.000000  10000.000000
25%    19.500000  17500.000000
50%    25.000000  25000.000000
75%    31.250000  32500.000000
max    35.000000  40000.000000

In [ ]:
#broadcasting in pandas
my_df["Salary"] = my_df["Salary"] + 10000
my_df

        name  Age          department  Salary
0     sanjay   20                  IT   20000
1  srivastav   30             Finance   30000
2   Lakshman   35  Charted Accountant   40000
3      Arjun   18       Bank Employee   50000

In [ ]:
#renaming a column this will refelct on main dataset because we used inplace
my_df.rename(columns = {"Salary": "salary"}, inplace = True)
my_df.rename(columns = {"Age":"age"}, inplace = True)

In [ ]:
my_df

        name  age          department  salary
0     sanjay   20                  IT   20000
1  srivastav   30             Finance   30000
2   Lakshman   35  Charted Accountant   40000
3      Arjun   18       Bank Employee   50000

In [ ]:
#check unique values in a dataset
my_df["age"].unique()
my_df["department"].unique()

array(['IT', 'Finance', 'Charted Accountant', 'Bank Employee'],
      dtype=object)

In [ ]:
#how many employees in each department, value_counts()
my_df["department"].value_counts()

department
IT                    1
Finance               1
Charted Accountant    1
Bank Employee         1
Name: count, dtype: int64

In [ ]:
#creation of new column
my_df["promoted salary"] = my_df["salary"] * 10
my_df

        name  age          department  salary  promoted salary
0     sanjay   20                  IT   20000           200000
1  srivastav   30             Finance   30000           300000
2   Lakshman   35  Charted Accountant   40000           400000
3      Arjun   18       Bank Employee   50000           500000

In [ ]:
my_df.isnull().sum()

name               0
age                0
department         0
salary             0
promoted salary    0
dtype: int64

In [ ]:
import numpy as np
my_df.loc[4] = ['Aarav', np.nan,"IT",np.nan,np.nan]

In [ ]:
# Define the data dictionary
data = {
    "name" : ["sanjay","srivastav","Lakshman","Arjun"],
    "Age" : [20,30,35,18],
    "department" : [np.nan,"Finance","Charted Accountant","Bank Employee"],
    "Salary" : [10000,20000,30000,40000]
}
print("Data dictionary defined:")
print(data)

Data dictionary defined:
{'name': ['sanjay', 'srivastav', 'Lakshman', 'Arjun'], 'Age': [20, 30, 35, 18], 'department': [nan, 'Finance', 'Charted Accountant', 'Bank Employee'], 'Salary': [10000, 20000, 30000, 40000]}

In [ ]:
# Create the DataFrame
import pandas as pd
my_df = pd.DataFrame(data)
print("\nDataFrame created:")
display(my_df)

DataFrame created:

        name  Age          department  Salary
0     sanjay   20                 NaN   10000
1  srivastav   30             Finance   20000
2   Lakshman   35  Charted Accountant   30000
3      Arjun   18       Bank Employee   40000

In [ ]:
# Renaming columns
my_df.rename(columns = {"Salary": "salary"}, inplace = True)
my_df.rename(columns = {"Age":"age"}, inplace = True)
print("\nColumns renamed:")
display(my_df)

Columns renamed:

        name  age          department  salary
0     sanjay   20                 NaN   10000
1  srivastav   30             Finance   20000
2   Lakshman   35  Charted Accountant   30000
3      Arjun   18       Bank Employee   40000

In [ ]:
# Creation of new column
my_df["promoted salary"] = my_df["salary"] * 10
print("\n'promoted salary' column added:")
display(my_df)

'promoted salary' column added:

        name  age          department  salary  promoted salary
0     sanjay   20                 NaN   10000           100000
1  srivastav   30             Finance   20000           200000
2   Lakshman   35  Charted Accountant   30000           300000
3      Arjun   18       Bank Employee   40000           400000

In [ ]:
# Modifying in series by adding a new row
import numpy as np
my_df.loc[4] = ['Aarav', np.nan,"IT",np.nan,np.nan]
print("\nNew row added:")
display(my_df)

New row added:

        name   age          department   salary  promoted salary
0     sanjay  20.0                 NaN  10000.0         100000.0
1  srivastav  30.0             Finance  20000.0         200000.0
2   Lakshman  35.0  Charted Accountant  30000.0         300000.0
3      Arjun  18.0       Bank Employee  40000.0         400000.0
4      Aarav   NaN                  IT      NaN              NaN

In [ ]:
my_df

        name   age          department   salary  promoted salary
0     sanjay  20.0                 NaN  10000.0         100000.0
1  srivastav  30.0             Finance  20000.0         200000.0
2   Lakshman  35.0  Charted Accountant  30000.0         300000.0
3      Arjun  18.0       Bank Employee  40000.0         400000.0
4      Aarav   NaN                  IT      NaN              NaN

In [ ]:
#data cleaning checking number of nulls in each column
my_df.isnull().sum()

name               0
age                1
department         1
salary             1
promoted salary    1
dtype: int64

In [ ]:
#dropping all nulls by using dropna() -> it will drop entire row that have null value
my_df.dropna()

        name   age          department   salary  promoted salary
1  srivastav  30.0             Finance  20000.0         200000.0
2   Lakshman  35.0  Charted Accountant  30000.0         300000.0
3      Arjun  18.0       Bank Employee  40000.0         400000.0

In [ ]:
my_df

        name   age          department   salary  promoted salary
0     sanjay  20.0                 NaN  10000.0         100000.0
1  srivastav  30.0             Finance  20000.0         200000.0
2   Lakshman  35.0  Charted Accountant  30000.0         300000.0
3      Arjun  18.0       Bank Employee  40000.0         400000.0
4      Aarav   NaN                  IT      NaN              NaN

In [ ]:
my_df.dropna(how = "any") #any row that had all the null values are dropped

        name   age          department   salary  promoted salary
1  srivastav  30.0             Finance  20000.0         200000.0
2   Lakshman  35.0  Charted Accountant  30000.0         300000.0
3      Arjun  18.0       Bank Employee  40000.0         400000.0

In [ ]:
my_df.dropna(how = "all") #all row that had all the null values are dropped
#here this table doesn't have null values entire row,so all rows are came as output

        name   age          department   salary  promoted salary
0     sanjay  20.0                 NaN  10000.0         100000.0
1  srivastav  30.0             Finance  20000.0         200000.0
2   Lakshman  35.0  Charted Accountant  30000.0         300000.0
3      Arjun  18.0       Bank Employee  40000.0         400000.0
4      Aarav   NaN                  IT      NaN              NaN

In [ ]:
#filling null values with a value
my_df.fillna(0)

        name   age          department   salary  promoted salary
0     sanjay  20.0                   0  10000.0         100000.0
1  srivastav  30.0             Finance  20000.0         200000.0
2   Lakshman  35.0  Charted Accountant  30000.0         300000.0
3      Arjun  18.0       Bank Employee  40000.0         400000.0
4      Aarav   0.0                  IT      0.0              0.0

In [ ]:
#it will fill null value with a mean value of all ages
my_df["age"].fillna(my_df["age"].mean())

0    20.00
1    30.00
2    35.00
3    18.00
4    25.75
Name: age, dtype: float64

In [ ]:
my_df["salary"].fillna(my_df["salary"].median())

0    10000.0
1    20000.0
2    30000.0
3    40000.0
4    25000.0
Name: salary, dtype: float64

In [ ]:
#tow types of filling Forward filling and backward filling ues key owrd called method
#top to bottom approach it will replace a null with a top row value
my_df["age"].fillna(method = "ffill")

/tmp/ipython-input-3779789816.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  my_df["age"].fillna(method = "ffill")

0    20.0
1    30.0
2    35.0
3    18.0
4    18.0
Name: age, dtype: float64

In [ ]:
#bottom to top approach it will replace a null with a bottom row value
#here age is replaced with NAN in this situvation better to use mean or median
my_df["age"].fillna(method = "bfill")

/tmp/ipython-input-478236586.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  my_df["age"].fillna(method = "bfill")

0    20.0
1    30.0
2    35.0
3    18.0
4     NaN
Name: age, dtype: float64

In [ ]:
my_df

        name   age          department   salary  promoted salary
0     sanjay  20.0                 NaN  10000.0         100000.0
1  srivastav  30.0             Finance  20000.0         200000.0
2   Lakshman  35.0  Charted Accountant  30000.0         300000.0
3      Arjun  18.0       Bank Employee  40000.0         400000.0
4      Aarav   NaN                  IT      NaN              NaN

In [ ]:
#changing name in a dataset

#this will change name in original dataset because we used my_df["name"]
my_df["name"] = my_df["name"].replace("sanjay","Nakul")
my_df

        name   age          department   salary  promoted salary
0      Nakul  20.0                 NaN  10000.0         100000.0
1  srivastav  30.0             Finance  20000.0         200000.0
2   Lakshman  35.0  Charted Accountant  30000.0         300000.0
3      Arjun  18.0       Bank Employee  40000.0         400000.0
4      Aarav   NaN                  IT      NaN              NaN

In [ ]:
import pandas as pd
import numpy as np

# Define the data dictionary
data = {
    "name" : ["sanjay","srivastav","Lakshman","Arjun"],
    "Age" : [20,30,35,18],
    "department" : ["IT","Finance","Charted Accountant","Bank Employee"],
    "Salary" : [10000,20000,30000,40000]
}

# Create the DataFrame
my_df = pd.DataFrame(data)

# Renaming columns
my_df.rename(columns = {"Salary": "salary"}, inplace = True)
my_df.rename(columns = {"Age":"age"}, inplace = True)

# Creation of new column
my_df["promoted salary"] = my_df["salary"] * 10

# Modifying in series by adding a new row
my_df.loc[4] = ['Aarav', np.nan,"IT",np.nan,np.nan]

#duplicating
my_df.dup = my_df[my_df.duplicated()]

/tmp/ipython-input-1331998275.py:26: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  my_df.dup = my_df[my_df.duplicated()]

In [ ]:
my_df

        name   age          department   salary  promoted salary
0     sanjay  20.0                  IT  10000.0         100000.0
1  srivastav  30.0             Finance  20000.0         200000.0
2   Lakshman  35.0  Charted Accountant  30000.0         300000.0
3      Arjun  18.0       Bank Employee  40000.0         400000.0
4      Aarav   NaN                  IT      NaN              NaN

In [ ]:
duplicate = my_df[my_df.duplicated()]
duplicate

Empty DataFrame
Columns: [name, age, department, salary, promoted salary]
Index: []

In [ ]:
#if we keep = "first" it means the last row is duplicated
duplicate = my_df[my_df.duplicated(keep = "first")]
duplicate

Empty DataFrame
Columns: [name, age, department, salary, promoted salary]
Index: []

In [ ]:
#if we keep = "last" it means the first row is duplicated, you can observe by seeing index,value is changed
duplicate = my_df[my_df.duplicated(keep = "last")]
duplicate

Empty DataFrame
Columns: [name, age, department, salary, promoted salary]
Index: []

In [ ]:
dropping_duplicates = my_df.drop_duplicates()
dropping_duplicates

        name   age          department   salary  promoted salary
0     sanjay  20.0                  IT  10000.0         100000.0
1  srivastav  30.0             Finance  20000.0         200000.0
2   Lakshman  35.0  Charted Accountant  30000.0         300000.0
3      Arjun  18.0       Bank Employee  40000.0         400000.0
4      Aarav   NaN                  IT      NaN              NaN

In [ ]:
my_df

        name   age          department   salary  promoted salary
0     sanjay  20.0                  IT  10000.0         100000.0
1  srivastav  30.0             Finance  20000.0         200000.0
2   Lakshman  35.0  Charted Accountant  30000.0         300000.0
3      Arjun  18.0       Bank Employee  40000.0         400000.0
4      Aarav   NaN                  IT      NaN              NaN

In [ ]:
 #invslid values
 #lambda functions -> python
 #here x is number of records
my_df["promoted salary"] = my_df["promoted salary"].apply(lambda x: x/6 if x > 50000 else x)
my_df

        name   age          department   salary  promoted salary
0     sanjay  20.0                  IT  10000.0     16666.666667
1  srivastav  30.0             Finance  20000.0     33333.333333
2   Lakshman  35.0  Charted Accountant  30000.0     50000.000000
3      Arjun  18.0       Bank Employee  40000.0     66666.666667
4      Aarav   NaN                  IT      NaN              NaN

In [ ]:
#apply and lambda
def multiply_age(x):
  return x*2

my_df["age"] = my_df["age"].apply(multiply_age)
my_df

        name   age          department   salary  promoted salary
0     sanjay  40.0                  IT  10000.0     16666.666667
1  srivastav  60.0             Finance  20000.0     33333.333333
2   Lakshman  70.0  Charted Accountant  30000.0     50000.000000
3      Arjun  36.0       Bank Employee  40000.0     66666.666667
4      Aarav   NaN                  IT      NaN              NaN

In [ ]:
my_df["age"] = my_df["age"].apply(lambda x: x/2)
my_df

        name   age          department   salary  promoted salary
0     sanjay  20.0                  IT  10000.0     16666.666667
1  srivastav  30.0             Finance  20000.0     33333.333333
2   Lakshman  35.0  Charted Accountant  30000.0     50000.000000
3      Arjun  18.0       Bank Employee  40000.0     66666.666667
4      Aarav   NaN                  IT      NaN              NaN

In [ ]:
#joins and merge
department_info = {
    "department" : ["HR","IT","Finance"],
    "Location" : ["New York","San Francisco","Chicago"],
    "Manager":["Laura","Steve","Nina"]
}
df2 = pd.DataFrame(department_info)
df2

  department       Location Manager
0         HR       New York   Laura
1         IT  San Francisco   Steve
2    Finance        Chicago    Nina

In [ ]:
#combine dataset using concat()
#this is example of row wise
pd.concat([my_df,df2])

,name,age,department,salary,promoted salary,Location,Manager
0,sanjay,20.0,IT,10000.0,16666.666667,NaN,NaN
1,srivastav,30.0,Finance,20000.0,33333.333333,NaN,NaN
2,Lakshman,35.0,Charted Accountant,30000.0,50000.000000,NaN,NaN
3,Arjun,18.0,Bank Employee,40000.0,66666.666667,NaN,NaN
4,Aarav,NaN,IT,NaN,NaN,NaN,NaN
0,NaN,NaN,HR,NaN,NaN,New York,Laura
1,NaN,NaN,IT,NaN,NaN,San Francisco,Steve
2,NaN,NaN,Finance,NaN,NaN,Chicago,Nina

In [ ]:
#concat by columns it will match department and give loc,manager to the same name by identifying same dept
pd.concat([my_df,df2],axis = 1)

,name,age,department,salary,promoted salary,department,Location,Manager
0,sanjay,20.0,IT,10000.0,16666.666667,HR,New York,Laura
1,srivastav,30.0,Finance,20000.0,33333.333333,IT,San Francisco,Steve
2,Lakshman,35.0,Charted Accountant,30000.0,50000.000000,Finance,Chicago,Nina
3,Arjun,18.0,Bank Employee,40000.0,66666.666667,NaN,NaN,NaN
4,Aarav,NaN,IT,NaN,NaN,NaN,NaN,NaN

In [ ]:
my_df.dropna(how = "any" , inplace = True)

In [ ]:
#only one department column is reflected it will automatically match the department and location,manager are same
pd.merge(my_df,df2, on = "department")

        name   age department   salary  promoted salary       Location Manager
0     sanjay  20.0         IT  10000.0     16666.666667  San Francisco   Steve
1  srivastav  30.0    Finance  20000.0     33333.333333        Chicago    Nina

In [ ]:
#importing a csv or csv file

data = pd.read_csv("/matches.csv")

In [ ]:
import os
print(os.listdir())

In [ ]:
data.shape

In [ ]:
data.head()

In [ ]:
data.isnull().sum()

In [ ]:
data.describe()

In [ ]:
data.info()

In [ ]:
#changing datatype of a column
data['date'] = pd.to_datetime(data['date'], format='%d-%m-%Y')

In [ ]:
data.info()